# This template contains steps to build the solution for a single architecture.

parameters:
  arch: ''
  config: 'Debug,Release'

jobs:
- job: build_${{ parameters.arch }}
  displayName: ${{ parameters.arch }}
  pool:
    vmImage: windows-latest
  variables:
  - name: runCodesignValidationInjection # We don't sign things currently
    value: false
  steps:
  - checkout: self
    submodules: true

  - task: VSBuild@1
    displayName: Build Solution (Debug)
    condition: and(succeeded(), contains('${{ parameters.config }}', 'Debug'))
    inputs:
      solution: xdp.sln
      platform: ${{ parameters.arch }}
      configuration: debug

  - task: VSBuild@1
    displayName: Build Solution (Release)
    condition: and(succeeded(), contains('${{ parameters.config }}', 'Release'))
    inputs:
      solution: xdp.sln
      platform: ${{ parameters.arch }}
      configuration: release

  - task: CopyFiles@2
    displayName: Filter Artifacts
    inputs:
      sourceFolder: artifacts/bin
      contents: '**/!(*.ilk|*.exp|*.lastcodeanalysissucceeded)'
      targetFolder: $(Build.ArtifactStagingDirectory)/bin

  - task: PublishBuildArtifacts@1
    displayName: Upload Artifacts
    inputs:
      artifactName: artifacts
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true
