# This template runs spinxsk.exe for a single architecture.

parameters:
- name: pool
  default: ''
- name: image
  default: ''
- name: arch
  default: 'x64'
- name: config
  default: 'Debug'
- name: ignoreFailures
  type: boolean
  default: false
- name: runtimeMinutes
  type: number
  default: 10
- name: timeoutMinutes
  type: number
  default: 15
- name: jobTimeoutMinutes
  type: number
  default: 25
- name: osName

jobs:
- job: spinxsk_${{ parameters.arch }}_${{ parameters.config }}_${{ parameters.osName }}_${{ replace(parameters.pool, '-', '_') }}
  displayName: spinxsk-${{ parameters.osName }}-${{ parameters.arch }}_${{ parameters.config }} (${{ parameters.pool }})
  # Either run on our self-hosted 'pool' or an AZP managed 'image'.
  ${{ if ne(parameters.pool, '') }}:
    pool:
      name: ${{ parameters.pool }}
      ${{ if ne(parameters.image, '') }}:
        demands: ImageOverride -equals ${{ parameters.image }}
    workspace:
      clean: all
  ${{ if eq(parameters.pool, '') }}:
    pool:
      vmImage: ${{ parameters.image }}
  continueOnError: ${{ parameters.ignoreFailures }}
  variables:
    runCodesignValidationInjection: false
    ${{ if lt(parameters.runtimeMinutes, 60) }}:
      logMode: 'File'
    ${{ if ge(parameters.runtimeMinutes, 60) }}:
      logMode: 'Memory'
  timeoutInMinutes: ${{ parameters.jobTimeoutMinutes }}
  steps:
  - checkout: self

  - task: PowerShell@2
    displayName: Check Drivers
    inputs:
      filePath: tools/check-drivers.ps1

  - task: PowerShell@2
    displayName: Prepare Machine
    inputs:
      filePath: tools/prepare-machine.ps1
      arguments: -ForTest -NoReboot

  - task: DownloadBuildArtifacts@0
    displayName: Download Artifacts
    inputs:
      artifactName: artifacts
      itemPattern: artifacts/bin/${{ parameters.arch }}_${{ parameters.config }}/**
      downloadPath: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Start Logging
    inputs:
      filePath: tools/log.ps1
      arguments: -Start -Name spinxsk -Profile SpinXsk.Verbose -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -LogMode ${{ variables.logMode }}

  - task: PowerShell@2
    displayName: Start Profiling
    condition: le(${{ parameters.runtimeMinutes }}, 10)
    inputs:
      filePath: tools/log.ps1
      arguments: -Start -Name spinxskcpu -Profile CpuCswitchSample.Verbose -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Install fndis
    timeoutInMinutes: 5
    inputs:
      filePath: tools/setup.ps1
      arguments: -Install fndis -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Install xdp
    timeoutInMinutes: 5
    inputs:
      filePath: tools/setup.ps1
      arguments: -Install xdp -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Install xdpmp
    timeoutInMinutes: 5
    inputs:
      filePath: tools/setup.ps1
      arguments: -Install xdpmp -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Run spinxsk
    timeoutInMinutes: ${{ parameters.timeoutMinutes }}
    inputs:
      filePath: tools/spinxsk.ps1
      arguments: -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -QueueCount 2 -Minutes ${{ parameters.runtimeMinutes }} -Verbose -Stats

  - task: PowerShell@2
    displayName: Uninstall xdpmp
    condition: always()
    timeoutInMinutes: 5
    inputs:
      filePath: tools/setup.ps1
      arguments: -Uninstall xdpmp -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Uninstall xdp
    condition: always()
    timeoutInMinutes: 5
    inputs:
      filePath: tools/setup.ps1
      arguments: -Uninstall xdp -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Uninstall fndis
    condition: always()
    timeoutInMinutes: 5
    inputs:
      filePath: tools/setup.ps1
      arguments: -Uninstall fndis -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Stop Profiling
    condition: and(le(${{ parameters.runtimeMinutes }}, 10), always())
    inputs:
      filePath: tools/log.ps1
      arguments: -Stop -Name spinxskcpu -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -NoTextConversion

  - task: PowerShell@2
    displayName: Stop Logging
    condition: always()
    inputs:
      filePath: tools/log.ps1
      ${{ if le(parameters.runtimeMinutes, 10) }}:
        arguments: -Stop -Name spinxsk -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}
      ${{ if gt(parameters.runtimeMinutes, 10) }}:
        arguments: -Stop -Name spinxsk -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -NoTextConversion

  - task: CopyFiles@2
    displayName: Stage Logs
    condition: always()
    inputs:
      sourceFolder: artifacts/logs
      contents: '**/!(*.ilk|*.exp|*.lastcodeanalysissucceeded)'
      targetFolder: $(Build.ArtifactStagingDirectory)/logs/${{ parameters.arch }}_${{ parameters.config }}_${{ parameters.osName }}_${{ parameters.pool }}

  - task: PublishBuildArtifacts@1
    displayName: Upload Logs
    condition: always()
    inputs:
      artifactName: artifacts
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true

  - task: PowerShell@2
    displayName: Cleanup Machine
    condition: always()
    inputs:
      filePath: tools/prepare-machine.ps1
      arguments: -Cleanup -ForTest -NoReboot

  - task: PowerShell@2
    displayName: Reboot (if necessary)
    condition: and(always(), eq(variables['NeedsReboot'],'true'))
    inputs:
      targetType: inline
      script: shutdown.exe /f /r /t 0 /c 'XDP Pipeline' /d u:4:5

  - task: PowerShell@2
    displayName: Check Drivers
    condition: always()
    inputs:
      filePath: tools/check-drivers.ps1
