# Continuous Integration (CI)

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
pr:
- main
- release/*

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:

- stage: build_debug
  displayName: Build (Debug)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Debug

- stage: build_release
  displayName: Build (Release)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Release

- stage: test_debug
  displayName: Functional Tests (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Debug
      osName: latest
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional
      image: MMS2016
      arch: x64
      config: Debug
      ignoreFailures: true
      osName: 2016
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional
      image: MMS2019
      arch: x64
      config: Debug
      osName: 2019

- stage: test_release
  displayName: Functional Tests (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Release
      osName: latest
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional
      image: MMS2016
      arch: x64
      config: Release
      ignoreFailures: true
      osName: 2016
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional
      image: MMS2019
      arch: x64
      config: Release
      osName: 2019

- stage: stress_debug
  displayName: Stress (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Debug
      osName: latest
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk
      image: MMS2016TLS
      ignoreFailures: true
      arch: x64
      config: Debug
      osName: 2016
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk
      image: MMS2019TLS
      ignoreFailures: true
      arch: x64
      config: Debug
      osName: 2019
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk
      image: MMS2022TLS
      arch: x64
      config: Debug
      osName: 2022

- stage: stress_release
  displayName: Stress (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Release
      osName: latest
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk
      image: MMS2016TLS
      ignoreFailures: true
      arch: x64
      config: Release
      osName: 2016
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk
      image: MMS2019TLS
      ignoreFailures: true
      arch: x64
      config: Release
      osName: 2019
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk
      image: MMS2022TLS
      arch: x64
      config: Release
      osName: 2022

- stage: devkit
  displayName: Dev Kit
  dependsOn: build_release
  jobs:
  - template: ./templates/devkit.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Release
