# Continuous Integration (CI)

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
pr:
- main
- release/*

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:

- stage: build_debug
  displayName: Build (Debug)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Debug

- stage: build_release
  displayName: Build (Release)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Release

- stage: test
  displayName: Functional Tests
  dependsOn: build_debug
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Debug
#  - template: ./templates/tests.yml
#    parameters:
#      image: windows-2022
#      arch: x64
#      config: Debug

- stage: stress
  displayName: Stress
  dependsOn:
  - build_debug
  - build_release
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Debug
  - template: ./templates/spinxsk.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Release
#  - template: ./templates/spinxsk.yml
#    parameters:
#      image: windows-2022
#      arch: x64
#      config: Release
