# Continuous Integration (CI)

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
pr:
- main
- release/*

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:

- stage: build
  displayName: Build
  dependsOn: []
  jobs:
#  - template: ./templates/build.yml
#    parameters:
#      arch: x86
  - template: ./templates/build.yml
    parameters:
      arch: x64
#  - template: ./templates/build.yml
#    parameters:
#      arch: arm
#  - template: ./templates/build.yml
#    parameters:
#      arch: arm64

- stage: test
  displayName: Functional Tests
  dependsOn: build
  jobs:
  - template: ./templates/tests.yml
    parameters:
      arch: x64
      config: Debug
#  - template: ./templates/tests.yml
#    parameters:
#      arch: x64
#      config: Release

- stage: stress
  displayName: Stress
  dependsOn: build
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      arch: x64
      config: Debug
  - template: ./templates/spinxsk.yml
    parameters:
      arch: x64
      config: Release
